<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>p</string>
		<string>i</string>
	</array>
	<key>name</key>
	<string>Progress ABL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/(?![^/]*?\*/)</string>
			<key>name</key>
			<string>comment.block.source.abl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single quoted string</string>
			<key>match</key>
			<string>('(?:'|.)*?')</string>
			<key>name</key>
			<string>string.single.source.abl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>""[a-zA-Z0-9_\.\-]+""</string>
			<key>name</key>
			<string>string.double.source.abl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>("(?!"[a-zA-Z]+)|""[a-zA-Z]+)</string>
			<key>end</key>
			<string>"(?!")</string>
			<key>name</key>
			<string>string.double.complex.abl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(~(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)|"")</string>
					<key>name</key>
					<string>constant.character.escape.abl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w)((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))</string>
			<key>name</key>
			<string>constant.numeric.source.abl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(true|false|yes|no(?!-))\b</string>
			<key>name</key>
			<string>constant.language.source.abl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\b(or|and|not|is)\b|(=|\+| - |/|&lt;|&gt;|,))</string>
			<key>name</key>
			<string>keyword.operator.source.abl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\b(no-undo|no-box|no-labels|no-lock|no-error|format|colon|label|initial|side-labels|width|primary|use-index)\b|@)</string>
			<key>name</key>
			<string>keyword.option.source.abl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(display|delete|create|update|assign|import( unformatted)?|input\s+(from|close)|with|skip)\b</string>
			<key>name</key>
			<string>keyword.statement.source.abl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(as|for(?!\s+(each|first|last)))\b</string>
			<key>name</key>
			<string>keyword.type.source.abl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.type.source.abl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.abl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(like)\s+([a-zA-Z0-9_\.-]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\b(if|available|down|where|else( if)?|for\s+(each|first|last)|do while|repeat(\s+while)?|find( first|last)?|then( do( transaction)?)?|next|page|quit)\b|(?&lt;!-)(\bend\b(?!\s+procedure)))</string>
			<key>name</key>
			<string>keyword.control.source.abl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(define\s+(((new\s+)?shared\s+)?(variable|stream|buffer)|((input|input-output|output)\s+parameter)|temp-table|query)|form)\b</string>
			<key>name</key>
			<string>storage.type.define.abl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(?&lt;!&amp;)(character|(?&lt;!-)handle|dataset-handle|dataset|field|(?&lt;!-)index|logical|integer|stream|frame [a-z]+)(?!\s*\()\b</string>
			<key>name</key>
			<string>storage.type.source.abl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(end (procedure))</string>
			<key>name</key>
			<string>storage.type.function.abl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.source.abl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(\b[a-z][a-z0-9_-]*?\b\s*)(?=\s*\(.*?\))</string>
			<key>name</key>
			<string>support.function.abl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.statement.source.abl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.source.abl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(run) ([a-z][a-z0-9_-]*?)\b(\s*\(.*?\))?</string>
			<key>name</key>
			<string>support.function.abl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.abl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.abl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(procedure)\s+([a-z0-9_-]+):</string>
			<key>name</key>
			<string>meta.function.source.abl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.source.abl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(\{[a-z0-9_\./-]+)</string>
			<key>name</key>
			<string>meta.function.bracket.abl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.source.abl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.function.bracket.abl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.abl</string>
	<key>uuid</key>
	<string>3bcebd60-f6cc-404f-930a-528f32956502</string>
</dict>
</plist>
